### ISSUE TITLE
Race in assertion tracker

### ISSUE THREAD

**Issue by banks** [antithesishq/antithesis-sdk-go#24]
Hi

I ran into an issue during local development of my workload.

When I enable assertion logging via ENV variable (i.e. so the assertions stop being no-ops). I hit panics caused by concurrent map access within tracker.go. It's easy to see why since each assertion directly operates on a Go `map` without any synchronisation.

The panic is not determinisic to reproduce locally (ironically!) and I assume that in the Antithesis environment this is also fine. It would be great to have this workable when locally debugging workloads.

To reliably see this though, I built my workload with `-race` and sure enough can immediately see the race detected. I've redacted parts of the stack that are in our own workload code but those shouldn't matter!

```
==================
WARNING: DATA RACE
Read at 0x00c00018e6d0 by goroutine 23:
  github.com/antithesishq/antithesis-sdk-go/assert.(*trackerInfo).emit()
      /Users/pbanks/src/go/pkg/mod/github.com/antithesishq/antithesis-sdk-go@v0.3.5/assert/tracker.go:60 +0xe4
  github.com/antithesishq/antithesis-sdk-go/assert.assertImpl()
      /Users/pbanks/src/go/pkg/mod/github.com/antithesishq/antithesis-sdk-go@v0.3.5/assert/assert.go:136 +0x370
  github.com/antithesishq/antithesis-sdk-go/assert.Sometimes()
...

Previous write at 0x00c00018e6d0 by goroutine 14:
  github.com/antithesishq/antithesis-sdk-go/assert.(*trackerInfo).emit()
      /Users/pbanks/src/go/pkg/mod/github.com/antithesishq/antithesis-sdk-go@v0.3.5/assert/tracker.go:64 +0x158
  github.com/antithesishq/antithesis-sdk-go/assert.assertImpl()
      /Users/pbanks/src/go/pkg/mod/github.com/antithesishq/antithesis-sdk-go@v0.3.5/assert/assert.go:136 +0x370
  github.com/antithesishq/antithesis-sdk-go/assert.Sometimes()
      /Users/pbanks/src/go/pkg/mod/github.com/antithesishq/antithesis-sdk-go@v0.3.5/assert/assert.go:85 +0x118
...
==================
```

Please let me know if I can provide any additional help!

It looks like just making the tracker into a struct that combines the map and a mutex would be sufficient to solve this. In production the instance would still be nil so would not cause any overhead but when logging is enabled it would allow safe map updates.

**Comment by herzogp** [comment]
Thanks Paul - I've added a mutex Lock/Unlock around operations on the `assertTracker` map.  
Also added atomic access to `hasEmitted` to ensure once-only output of `versionMessage()`

Testing now, and I'll get an update posted once that is done

**Comment by herzogp** [comment]
Updated in Go SDK v0.3.8 - `98854a587a3bf3229b4438ca9d667475795ac287`
